-- MySQL Script generated by MySQL Workbench
-- Fri Sep 23 19:58:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Devitter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Devitter` ;

-- -----------------------------------------------------
-- Schema Devitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Devitter` DEFAULT CHARACTER SET utf8 ;
USE `Devitter` ;

-- -----------------------------------------------------
-- Table `Devitter`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devitter`.`User` ;

CREATE TABLE IF NOT EXISTS `Devitter`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(254) NOT NULL UNIQUE,
  `username` VARCHAR(45) NOT NULL UNIQUE,
  `biography` VARCHAR(160) NULL,
  `password` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devitter`.`Tool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devitter`.`Tool` ;

CREATE TABLE IF NOT EXISTS `Devitter`.`Tool` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devitter`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devitter`.`Post` ;

CREATE TABLE IF NOT EXISTS `Devitter`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commented_post_id` INT NULL,
  `content` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(1) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Post_Post1_idx` (`commented_post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Devitter`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Post1`
    FOREIGN KEY (`commented_post_id`)
    REFERENCES `Devitter`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devitter`.`Like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devitter`.`Like` ;

CREATE TABLE IF NOT EXISTS `Devitter`.`Like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Like_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Like_Post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Devitter`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_Post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `Devitter`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devitter`.`Follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devitter`.`Follow` ;

CREATE TABLE IF NOT EXISTS `Devitter`.`Follow` (
  `followed_id` INT NOT NULL,
  `follower_id` INT NOT NULL,
  PRIMARY KEY (`followed_id`),
  INDEX `fk_Follow_User1_idx` (`follower_id` ASC) VISIBLE,
  CONSTRAINT `fk_Follow_User1`
    FOREIGN KEY (`follower_id`)
    REFERENCES `Devitter`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Devitter`.`User_Tool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Devitter`.`User_Tool` ;

CREATE TABLE IF NOT EXISTS `Devitter`.`User_Tool` (
  `user_id` INT NOT NULL,
  `tool_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`, `tool_id`),
  INDEX `fk_User_has_Tool_Tool1_idx` (`tool_id` ASC) VISIBLE,
  INDEX `fk_User_has_Tool_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Tool_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `Devitter`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Tool_Tool1`
    FOREIGN KEY (`tool_id`)
    REFERENCES `Devitter`.`Tool` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
